plugins {
    id 'java'
    id 'maven-publish'
}

group = "ome"
version = "8.6.0-SNAPSHOT"


repositories {
    mavenCentral()
    maven {
        url = 'https://artifacts.openmicroscopy.org/artifactory/ome.releases/'
    }
    maven {
        url = 'https://maven.scijava.org/content/repositories/thirdparty/'
    }
    maven {
        name = 'Unidata'
        url = 'https://artifacts.openmicroscopy.org/artifactory/unidata-releases'
    }
}

dependencies {
    implementation "ome:formats-bsd:8.5.0"
    implementation "ch.qos.logback:logback-classic:1.3.16"
}

task sourcesJar(type: Jar, dependsOn: classes) {
    archiveClassifier = 'sources'
    from sourceSets.main.allSource
}

task javadocJar(type: Jar, dependsOn: javadoc) {
    archiveClassifier = 'javadoc'
    from javadoc.destinationDir
}

java {
    withSourcesJar()
    withJavadocJar()
}

task exec(type: JavaExec) {
    mainClass = 'ExampleSuite'
    classpath = sourceSets.main.runtimeClasspath
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifact sourcesJar
            artifact javadocJar
        }
    }
}
